version: "3.8"

services:
  db:
    image: postgres:17.5-alpine3.22
    container_name: mini-ecommerce-db
    restart: unless-stopped
    environment:
      POSTGRES_DB: project-mini-ecommerce
      POSTGRES_USER: huydo
      POSTGRES_PASSWORD: 123456
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
volumes:
  pgdata: